spring.application.name=Gateway
server.port=8080

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Route for AUTH-SERVICE  (spring.application.name=auth-service)
spring.cloud.gateway.routes[0].id=harmoni-auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Route for MASTER-SERVICE  (spring.application.name=Master)
spring.cloud.gateway.routes[1].id=harmoni-master-service
spring.cloud.gateway.routes[1].uri=lb://master
spring.cloud.gateway.routes[1].predicates[0]=Path=/harmoni/**

# CORS
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*

# MUST match jwt.secret in Auth and Master services
jwt.secret=your-very-long-and-super-secret-key-that-is-at-least-256-bits-long-for-hs256
